### ISSUE TITLE
It is not possible to import the testing token by entering the address in the token search field

### ISSUE THREAD

**Issue by MilanVojnovic95** [metrom-xyz/monorepo#66]
When creating a campaign at the 'rewards' step, if the user clicks on the Token, a modal window opens, which should contain the search and token display.
Testing tokens are not pre-read and displayed in the list, so I should enter them manually, ie. entering the address of the token in the search field, but it is not possible to do that for the first 5 to 10 minutes after opening that modal window. That option appears later.

Even when that option appears after pasting the token address, that token is not recognized and it is not possible to enter it manually.

Tested on Dev and Stage environment.

https://www.loom.com/share/c4f52ab6223d48aaa3a583b51be84598?sid=276eb3be-c1bf-482a-88fd-1ae201897aed

**Comment by guerrap** [comment]
The import token feature has been remove, only whitelisted tokens can be used as rewards.
